package com.bot.eyelashes.enums;

public enum BotState {
    ASK_NAME,ASK_SURNAME,ASK_DATE, ASK_ADDRESS, ASK_PHONE, ASK_ACTIVITY, ASK_DEFAULT, ASK_TIME_FROM,ASK_TIME_TO, ASK_READY, REGISTERED, PROFILE_FIELD, FILLING_PROFILE,NONE;
}
