spring:
  datasource:
    username: doadmin
    hikari:
      maximum-pool-size: '5'
    url: jdbc:postgresql://db-postgresql-fra1-69062-do-user-11372412-0.b.db.ondigitalocean.com:25060/eyelashes
    password: AVNS_ClMzraDTLV4mXFQ
  jpa:
    generate-ddl: 'true'
    properties:
      javax:
        persistence:
          query:
            timeout: '6000000'


telegram:
  nameBot: '@ndfsdjkgnj_bot'
  tokenBot: '5590216654:AAEUna_vQ97Qu9NCktXI2iy96ekLlihty20'
