spring:
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
    url: jdbc:postgresql://localhost:5432/Bot
    password: admin
  jpa:
    generate-ddl: 'true'
    properties:
      javax:
        persistence:
          query:
            timeout: '6000000'
telegram:
  nameBot: '@BeautyEyelashesBot'
  tokenBot: '5531596418:AAFw9TtWSvIgZSD_-KpRi0JUDz1LWXmfQSY'
  messageTextInfo : 'Amd'
