spring:
  datasource:
    username: postgres
    hikari:
      maximum-pool-size: '5'
    url: jdbc:postgresql://localhost:5432/Bot
    password: admin
  jpa:
    generate-ddl: 'true'
    properties:
      javax:
        persistence:
          query:
            timeout: '6000000'
telegram:
  nameBot: '@ndfsdjkgnj_bot'
  tokenBot: '5590216654:AAGzsNWK1xsfSxqZ-waJf_C2g-4VxLGZ8ok'
  messageTextInfo : 'Amd'
